# Generated by Django 4.2.4 on 2023-09-25 11:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0013_rename_job_title_id_technician_job_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("WEEKLY", "WEEKLY"), ("MONTHLY", "MONTHLY")],
                        default="WEEKLY",
                        max_length=60,
                        verbose_name="frequency",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("description", models.CharField(max_length=1000, verbose_name="description")),
                ("image", models.ImageField(blank=True, null=True, upload_to="job_images/", verbose_name="image")),
                (
                    "max_budget",
                    models.PositiveIntegerField(
                        help_text="The maximum amount a client can afford for this service", verbose_name="max budget"
                    ),
                ),
                ("location_address", models.CharField(max_length=1000, verbose_name="location address")),
                ("location_longitude", models.FloatField(verbose_name="location longitude")),
                ("location_latitude", models.FloatField(verbose_name="location latitude")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="The time period for the maintenance (in days)", verbose_name="duration"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.client", verbose_name="client"
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.technician",
                        verbose_name="technician",
                    ),
                ),
                (
                    "technician_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.techniciantype",
                        verbose_name="technician type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance",
                "verbose_name_plural": "Maintenances",
                "ordering": ["-created_at"],
            },
        ),
    ]
