# Generated by Django 4.2.4 on 2023-10-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="maintenance_images/", verbose_name="image"),
        ),
    ]
