# Generated by Django 4.2.4 on 2023-10-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0003_remove_maintenance_max_budget_maintenance_max_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
