# Generated by Django 4.2.4 on 2023-10-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolcategory",
            name="description",
            field=models.TextField(
                blank=True, default=str, max_length=800, null=True, verbose_name="category description"
            ),
        ),
        migrations.AlterField(
            model_name="toolcategory",
            name="name",
            field=models.CharField(max_length=256, unique=True, verbose_name="category name"),
        ),
    ]
