# Generated by Django 4.2.4 on 2023-10-16 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0002_alter_toolcategory_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolcategory",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
