# Generated by Django 4.2.4 on 2023-10-17 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0003_toolcategory_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="toolcategory",
            options={"verbose_name": "Tool Category", "verbose_name_plural": "Tool Categories"},
        ),
        migrations.AddField(
            model_name="toolcategory",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tool_categories_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
