# Generated by Django 4.2.4 on 2023-10-19 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0004_alter_toolcategory_options_toolcategory_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=256, unique=True, verbose_name="tool's name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default=str, max_length=800, null=True, verbose_name="tool's description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="tools_images/", verbose_name="tool's image"),
                ),
                ("negotiable", models.BooleanField(default=False)),
                ("price", models.FloatField(default=0.0, verbose_name="tool's price")),
                ("is_rented", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="tools.toolcategory",
                        verbose_name="tool's category",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tools_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="tools' owner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
