# Generated by Django 4.2.4 on 2023-10-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0005_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(max_length=256, verbose_name="tool's name"),
        ),
    ]
