# Generated by Django 4.2.4 on 2023-10-21 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0006_alter_tool_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tool",
            options={"verbose_name": "Tool", "verbose_name_plural": "Tools"},
        ),
    ]
