# Generated by Django 4.2.4 on 2023-10-27 06:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_user_profile_picture"),
        ("tools", "0008_tool_price_currency_alter_tool_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tool",
            name="image",
        ),
        migrations.CreateModel(
            name="ToolImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("image", models.ImageField(upload_to="tools/images", verbose_name="tool's image")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_images_created",
                        to="users.technician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Image",
                "verbose_name_plural": "Tool Images",
            },
        ),
        migrations.AddField(
            model_name="tool",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="tools", to="tools.toolimage", verbose_name="tool's images"
            ),
        ),
    ]
