# Generated by Django 4.2.4 on 2023-10-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0009_remove_tool_image_toolimage_tool_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("rental_duration", models.IntegerField(default=1, verbose_name="rental duration")),
                ("price", models.FloatField(default=0.0, verbose_name="negotiation price")),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="request owner",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_requests",
                        to="tools.tool",
                        verbose_name="tool requested",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
