# Generated by Django 4.2.4 on 2023-10-23 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0010_rentalrequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rentalrequest",
            old_name="technician",
            new_name="request_owner",
        ),
    ]
