# Generated by Django 4.2.4 on 2023-10-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0011_rename_technician_rentalrequest_request_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="pricing_period",
            field=models.CharField(choices=[("hour", "HOUR"), ("day", "DAILY")], default="hour"),
        ),
    ]
