# Generated by Django 4.2.4 on 2023-10-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0012_tool_pricing_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="pricing_period",
            field=models.CharField(choices=[("hour", "HOUR"), ("daily", "DAILY")], default="hour"),
        ),
    ]
