# Generated by Django 4.2.4 on 2023-10-25 14:34

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0013_alter_tool_pricing_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalrequest",
            name="request_owner",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="owner",
        ),
    ]
