# Generated by Django 4.2.4 on 2023-10-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0015_rentalrequest_price_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalrequest",
            name="is_accepted",
        ),
        migrations.AddField(
            model_name="rentalrequest",
            name="request_status",
            field=models.CharField(
                choices=[("accepted", "ACCEPTED"), ("rejected", "REJECTED"), ("pending", "PENDING")],
                default="pending",
                verbose_name="request status",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="pricing_period",
            field=models.CharField(choices=[("hourly", "HOURLY"), ("daily", "DAILY")], default="hourly"),
        ),
    ]
