# Generated by Django 4.2.4 on 2023-11-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0016_remove_rentalrequest_is_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="color_codes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tool",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "NEW"),
                    ("used: like-new", "USED: LIKE-NEW"),
                    ("used: very good", "USED: VERY GOOD"),
                    ("used: good", "USED: GOOD"),
                    ("used: worn", "USED: WORN"),
                ],
                default="NEW",
                verbose_name="tool's condition",
            ),
        ),
    ]
