# Generated by Django 4.2.4 on 2023-11-17 06:05

from re import T
from django.db import migrations


def create_tool_category(apps, schema_editor):
    ToolCategory = apps.get_model("tools", "ToolCategory")
    categories = [
        "Adhesives, Sealants & Fillers",
        "Air Tools & Compressors",
        "Automotive Tools",
        "Books, Guides & Videos",
        "Cleaning & Drainage",
        "Cycle & Motorcycle",
        "Decorating & Tiling Tools",
        "Detectors & Testing Tools",
        "Electrical",
        "Engineering Tools",
        "Fans & Heaters",
        "Fixings & Fasteners",
        "Garden Tools",
        "Hand Tools",
        "Household & Hardware",
        "Ladders & Sack Trucks",
        "Lighting & Torches",
        "Machinery",
        "Materials",
        "Measuring Tools",
        "Paints & Varnishes",
        "Plumbing Tools",
        "Power Tool Accessories",
        "Power Tools",
        "Safety & Detectors",
        "Security",
        "Tool Boxes & Storage",
        "Tool Kits",
        "Travel & Outdoors",
        "Welding Tools",
        "Workbenches & Vices",
        "Workwear",
        "Others",
    ]

    categories_objs = [ToolCategory(name=category) for category in categories]
    ToolCategory.objects.bulk_create(categories_objs)


def reverse_create_tool_category(apps, schema_editor):
    ToolCategory = apps.get_model("tools", "ToolCategory")
    ToolCategory.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0017_tool_color_codes_tool_condition"),
    ]

    operations = [
        migrations.RunPython(create_tool_category, reverse_create_tool_category),
    ]
