# Generated by Django 4.2.4 on 2023-12-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0018_auto_20231117_0605"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="tool's quantity"),
        ),
    ]
