# Generated by Django 4.2.4 on 2023-12-15 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0020_toolnegotiation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="toolnegotiation",
            old_name="negotiation_status",
            new_name="status",
        ),
    ]
