# Generated by Django 4.2.4 on 2023-12-15 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0021_rename_negotiation_status_toolnegotiation_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="toolnegotiation",
            old_name="negotiation_owner",
            new_name="negotiator",
        ),
    ]
