# Generated by Django 4.2.4 on 2023-12-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_alter_client_user_alter_technician_user"),
        ("tools", "0022_rename_negotiation_owner_toolnegotiation_negotiator"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolnegotiation",
            name="tool_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="negotiations",
                to="users.technician",
                verbose_name="tool owner",
            ),
        ),
    ]
