# Generated by Django 4.2.4 on 2023-12-16 18:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0023_toolnegotiation_tool_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolnegotiation",
            name="attempts",
            field=models.IntegerField(default=0, verbose_name="attempts"),
        ),
        migrations.AlterField(
            model_name="toolnegotiation",
            name="negotiator",
            field=models.ForeignKey(
                help_text="The user (client/technician) who is negotiating the tool",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="negotiations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="negotiator",
            ),
        ),
        migrations.AlterField(
            model_name="toolnegotiation",
            name="offered_price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                default_currency="NGN",
                max_digits=14,
                null=True,
                verbose_name="offered price",
            ),
        ),
        migrations.AlterField(
            model_name="toolnegotiation",
            name="status",
            field=models.CharField(
                choices=[("accepted", "accepted"), ("rejected", "rejected"), ("pending", "pending")],
                default="pending",
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="toolnegotiation",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiations",
                to="tools.tool",
                verbose_name="tool",
            ),
        ),
    ]
