# Generated by Django 4.2.4 on 2023-09-16 06:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0008_remove_verificationcode_verified_client_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("description", models.CharField(max_length=1000, verbose_name="description")),
                ("location_address", models.CharField(max_length=1000, verbose_name="location address")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPENED", "OPENED"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("DONE", "DONE"),
                            ("CANCELLED", "CANCELLED"),
                            ("SCHEDULED", "SCHEDULED"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("PAID", "PAID"),
                        ],
                        default="OPENED",
                        max_length=60,
                        verbose_name="status",
                    ),
                ),
                ("location_longitude", models.FloatField(verbose_name="location longitude")),
                ("location_latitude", models.FloatField(verbose_name="location latitude")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="The time period for the job (in days)", verbose_name="duration"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.client", verbose_name="client"
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.technician", verbose_name="technician"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
