# Generated by Django 4.2.4 on 2023-09-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_verificationcode_verified_client_updated_at_and_more"),
        ("jobs", "0002_job_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("OPENED", "OPENED"),
                    ("IN_PROGRESS", "IN_PROGRESS"),
                    ("DONE", "DONE"),
                    ("CANCELLED", "CANCELLED"),
                    ("SCHEDULED", "SCHEDULED"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("PAID", "PAID"),
                ],
                default="DRAFT",
                max_length=60,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.technician",
                verbose_name="technician",
            ),
        ),
    ]
