# Generated by Django 4.2.4 on 2023-10-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_alter_job_status_alter_job_technician"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="max_budget",
            field=models.PositiveIntegerField(
                default=10000,
                help_text="The maximum amount a client can afford for this service",
                verbose_name="max budget",
            ),
            preserve_default=False,
        ),
    ]
