# Generated by Django 4.2.4 on 2023-10-11 11:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_remove_user_is_verified_again"),
        ("jobs", "0004_job_max_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ping",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("distance_from_client", models.FloatField(verbose_name="distance from client")),
                (
                    "status",
                    models.CharField(
                        choices=[("REQUESTED", "REQUESTED"), ("DECLINED", "DECLINED"), ("ACCEPTED", "ACCEPTED")],
                        default="REQUESTED",
                        max_length=60,
                        verbose_name="status",
                    ),
                ),
                (
                    "max_budget",
                    models.PositiveIntegerField(
                        help_text="The maximum amount a client can afford for this service", verbose_name="max budget"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.client", verbose_name="client"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="jobs.job", verbose_name="job"),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.technician", verbose_name="technician"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ping",
                "verbose_name_plural": "Pings",
                "ordering": ["-created_at"],
            },
        ),
    ]
