# Generated by Django 4.2.4 on 2023-10-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_job_max_price_job_max_price_currency_job_min_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="require_technicians_immediately",
            field=models.BooleanField(default=False, verbose_name="require technicians immediately"),
        ),
    ]
