# Generated by Django 4.2.4 on 2023-10-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_ping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ping",
            name="distance_from_client",
            field=models.FloatField(help_text="Value is in kilometers", verbose_name="distance from client"),
        ),
    ]
