# Generated by Django 4.2.4 on 2023-10-19 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_job_require_technicians_immediately"),
        ("jobs", "0006_alter_ping_distance_from_client"),
    ]

    operations = []
