# Generated by Django 4.2.4 on 2023-10-19 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_merge_20231019_1617"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="max_budget",
        ),
    ]
