# Generated by Django 4.2.4 on 2023-11-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_remove_ping_max_budget_ping_price_quote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="ping_request_cycle",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Helps track the number of cycles this job owner has made job request pings",
                verbose_name="ping request cycle",
            ),
        ),
    ]
