# Generated by Django 4.2.4 on 2023-11-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_job_ping_request_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="require_technicians_next_day",
            field=models.BooleanField(default=False, verbose_name="require technicians next day"),
        ),
    ]
