# Generated by Django 4.2.4 on 2023-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0012_job_require_technicians_next_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ping",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "REQUESTED"),
                    ("DECLINED", "DECLINED"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("NEGOTIATING", "NEGOTIATING"),
                    ("EXPIRED", "EXPIRED"),
                ],
                default="REQUESTED",
                max_length=60,
                verbose_name="status",
            ),
        ),
    ]
