# Generated by Django 4.2.4 on 2023-11-10 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0013_alter_ping_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="completion_state",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MaxValueValidator(10.0)],
                verbose_name="completion state",
            ),
        ),
    ]
