# Generated by Django 4.2.4 on 2023-11-21 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0015_ping_transaction_cost_ping_transaction_cost_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ping",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="pings", to="jobs.job", verbose_name="job"
            ),
        ),
    ]
