# Generated by Django 4.2.4 on 2023-12-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0016_alter_ping_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("OPENED", "OPENED"),
                    ("NOT_VERIFIED", "NOT_VERIFIED"),
                    ("PENDING", "PENDING"),
                    ("VERIFIED", "VERIFIED"),
                    ("CANCELLED", "CANCELLED"),
                    ("SCHEDULED", "SCHEDULED"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("PAID", "PAID"),
                ],
                default="DRAFT",
                max_length=60,
                verbose_name="status",
            ),
        ),
    ]
