# Generated by Django 4.2.4 on 2023-12-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0017_alter_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("IN_PROGRESS", "IN_PROGRESS"),
                    ("DONE", "DONE"),
                    ("VERIFIED", "VERIFIED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PENDING",
                max_length=60,
                verbose_name="status",
            ),
        ),
    ]
