# Generated by Django 4.2.4 on 2023-11-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0028_remove_technician_certificate_and_more"),
        ("jobs", "0009_job_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPriceQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.FloatField(verbose_name="price")),
                (
                    "is_accepted",
                    models.BooleanField(default=False, verbose_name="is accepted"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.job",
                        verbose_name="job",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.technician",
                        verbose_name="technician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Price Quotation",
                "verbose_name_plural": "Job Price Quotations",
            },
        ),
        migrations.AddConstraint(
            model_name="jobpricequotation",
            constraint=models.UniqueConstraint(
                fields=("technician", "job"),
                name="unique_technician_job_price_quotation",
            ),
        ),
    ]
