# Generated by Django 4.2.4 on 2023-11-13 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_jobincrementalpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobincrementalpayment",
            name="client_state",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[django.core.validators.MaxValueValidator(10.0)],
                verbose_name="client state",
            ),
        ),
        migrations.AddField(
            model_name="jobincrementalpayment",
            name="technician_state",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[django.core.validators.MaxValueValidator(10.0)],
                verbose_name="technician state",
            ),
        ),
        migrations.AlterField(
            model_name="jobincrementalpayment",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
