# Generated by Django 4.2.4 on 2023-12-10 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_alter_client_user_alter_technician_user"),
        ("payments", "0004_jobincrementalpayment_client_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("slug", models.SlugField(max_length=255, verbose_name="slug")),
                ("code", models.CharField(max_length=255, verbose_name="code")),
                ("longcode", models.CharField(max_length=255, verbose_name="longcode")),
                ("gateway", models.CharField(blank=True, max_length=255, null=True, verbose_name="gateway")),
                ("pay_with_bank", models.BooleanField(default=False, verbose_name="pay with bank")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("country", models.CharField(blank=True, max_length=255, null=True, verbose_name="country")),
                (
                    "currency",
                    models.CharField(blank=True, default="NGN", max_length=3, null=True, verbose_name="currency"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TechnicianBankAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="account name")),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="account number"),
                ),
                (
                    "routing_number",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="routing number"),
                ),
                ("account_type", models.CharField(blank=True, max_length=255, null=True, verbose_name="account type")),
                (
                    "paystack_recipient_code",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="paystack recipient code"),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_bank_accounts",
                        to="payments.bank",
                        verbose_name="bank",
                    ),
                ),
                (
                    "technician",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_bank_account",
                        to="users.technician",
                        verbose_name="technician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technician Bank Account",
                "verbose_name_plural": "Technician Bank Accounts",
            },
        ),
    ]
