# Generated by Django 4.2.4 on 2023-12-10 12:52

import json
from django.db import migrations

def load_paystack_banks_data(apps, schema_editor):
    # Path to your JSON file
    Bank = apps.get_model('payments', 'Bank')
    file_path = 'polymarq_backend/apps/payments/paystack/banks.json'

    # Open and load the JSON file
    with open(file_path, 'r') as file:
        data = json.load(file)

    # Create a list of Bank objects
    banks = [Bank(**entry) for entry in data]

    # Use bulk_create to insert all records at once
    Bank.objects.bulk_create(banks)

def reverse_load_paystack_banks_data(apps, schema_editor):
    Bank = apps.get_model('payments', 'Bank')
    Bank.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_bank_technicianbankaccount"),
    ]

    operations = [
        migrations.RunPython(load_paystack_banks_data, reverse_load_paystack_banks_data),
    ]
