# Generated by Django 4.2.4 on 2023-12-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_jobincrementalpayment_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianbankaccount",
            name="paystack_subaccount_code",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="paystack subaccount code"),
        ),
    ]
