# Generated by Django 4.2.4 on 2023-12-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_technicianbankaccount_paystack_subaccount_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobincrementalpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="initiated",
                max_length=255,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="toolpurchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="initiated",
                max_length=255,
                verbose_name="status",
            ),
        ),
    ]
