# Generated by Django 4.2.4 on 2023-12-16 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0030_alter_client_user_alter_technician_user"),
        ("payments", "0010_jobinitialpayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toolpurchase",
            name="technician",
        ),
        migrations.AddField(
            model_name="toolpurchase",
            name="buyer",
            field=models.ForeignKey(
                help_text="The user (client/technician) who bought the tool",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tool_purchases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="buyer user",
            ),
        ),
        migrations.AddField(
            model_name="toolpurchase",
            name="seller",
            field=models.ForeignKey(
                help_text="The technician who sold the tool",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tool_purchases",
                to="users.technician",
                verbose_name="technician",
            ),
        ),
    ]
