# Generated by Django 4.2.4 on 2023-12-05 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(max_length=256, verbose_name="notification's title")),
                ("body", models.TextField(verbose_name="notification's body")),
                ("is_read", models.BooleanField(default=False)),
                ("notification_type", models.CharField(null=True, verbose_name="notification's type")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="notification's recipient (user)",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
