# Generated by Django 4.2.4 on 2023-12-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("JOB", "JOB"),
                    ("TOOL", "TOOL"),
                    ("MAINTENANCE", "MAINTENANCE"),
                    ("PAYMENT", "PAYMENT"),
                    ("ACCOUNT", "ACCOUNT"),
                    ("OTHER", "OTHER"),
                ],
                default="OTHER",
                null=True,
                verbose_name="notification's type",
            ),
        ),
    ]
