# Generated by Django 4.2.4 on 2023-12-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="payload",
            field=models.JSONField(null=True, verbose_name="notification's payload"),
        ),
    ]
