# Generated by Django 4.2.4 on 2023-12-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notification_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("JOB", "JOB"),
                    ("TOOL-NEGOTIATION", "TOOL-NEGOTIATION"),
                    ("TOOL-NEGOTIATION-RESPONSE", "TOOL-NEGOTIATION-RESPONSE"),
                    ("TOOL-RENTAL", "TOOL-RENTAL"),
                    ("MAINTENANCE", "MAINTENANCE"),
                    ("PAYMENT", "PAYMENT"),
                    ("ACCOUNT", "ACCOUNT"),
                    ("OTHER", "OTHER"),
                ],
                default="OTHER",
                null=True,
                verbose_name="notification's type",
            ),
        ),
    ]
