# Generated by Django 4.2.4 on 2023-08-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_verificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user has verified their accounts.",
                verbose_name="verified",
            ),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="verified"),
        ),
    ]
