# Generated by Django 4.2.4 on 2023-09-04 21:52

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_is_verified_verificationcode_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("user_manager", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[("company", "Company"), ("individual", "Individual")],
                default="individual",
                max_length=20,
                verbose_name="account type",
            ),
        ),
    ]
