# Generated by Django 4.2.4 on 2023-09-07 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_usertype_alter_user_managers_user_account_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserType",
        ),
    ]
