# Generated by Django 4.2.4 on 2023-09-09 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_delete_usertype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="account_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(
                default=False, help_text="Designates whether this user is a client.", verbose_name="client"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_technician",
            field=models.BooleanField(
                default=False, help_text="Designates whether this user is a technician.", verbose_name="technician"
            ),
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technician",
                "verbose_name_plural": "Technicians",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "account_type",
                    models.CharField(
                        choices=[("company", "Company"), ("individual", "Individual")],
                        default="individual",
                        max_length=20,
                        verbose_name="account type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-created_at"],
            },
        ),
    ]
