# Generated by Django 4.2.4 on 2023-09-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_verificationcode_verified_client_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="technician",
            name="job_title",
            field=models.CharField(default=str, max_length=256),
        ),
        migrations.AddField(
            model_name="technician",
            name="professional_summary",
            field=models.TextField(default=str, max_length=800),
        ),
    ]
