# Generated by Django 4.2.4 on 2023-09-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_technician_experience_technician_job_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicianType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="technician",
            old_name="experience",
            new_name="years_of_experience",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="job_title",
        ),
        migrations.AddField(
            model_name="technician",
            name="address",
            field=models.TextField(default=str, max_length=800),
        ),
        migrations.AddField(
            model_name="technician",
            name="job_title_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technicians",
                to="users.techniciantype",
            ),
        ),
    ]
