# Generated by Django 4.2.4 on 2023-09-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_technician_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techniciantype",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
