# Generated by Django 4.2.4 on 2023-09-20 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_techniciantype_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="technician",
            old_name="job_title_id",
            new_name="job_title",
        ),
    ]
