# Generated by Django 4.2.4 on 2023-09-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_rename_job_title_id_technician_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
