# Generated by Django 4.2.4 on 2023-09-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_client_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.TextField(default=str),
        ),
    ]
