# Generated by Django 4.2.4 on 2023-09-29 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_client_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technician",
            name="address",
        ),
        migrations.AddField(
            model_name="technician",
            name="certificate",
            field=models.ImageField(
                blank=True, null=True, upload_to="technicians_certificate/", verbose_name="technicians certificate"
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="city",
            field=models.CharField(default=str, max_length=256, verbose_name="city"),
        ),
        migrations.AddField(
            model_name="technician",
            name="country",
            field=models.CharField(default=str, max_length=256, verbose_name="country"),
        ),
        migrations.AddField(
            model_name="technician",
            name="local_government_area",
            field=models.CharField(default=str, max_length=256, verbose_name="LGA"),
        ),
        migrations.AddField(
            model_name="technician",
            name="services",
            field=models.TextField(default=str, max_length=800, verbose_name="services offered"),
        ),
        migrations.AddField(
            model_name="technician",
            name="work_address",
            field=models.TextField(default=str, max_length=800, verbose_name="work address"),
        ),
        migrations.AlterField(
            model_name="technician",
            name="job_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technicians",
                to="users.techniciantype",
                verbose_name="job title",
            ),
        ),
        migrations.AlterField(
            model_name="technician",
            name="professional_summary",
            field=models.TextField(default=str, max_length=800, verbose_name="professional summary"),
        ),
        migrations.AlterField(
            model_name="technician",
            name="years_of_experience",
            field=models.IntegerField(default=0, verbose_name="years of experience"),
        ),
    ]
