# Generated by Django 4.2.4 on 2023-10-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_remove_technician_address_technician_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="technicians_certificate/", verbose_name="technician certificate"
            ),
        ),
    ]
