# Generated by Django 4.2.4 on 2023-10-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_technician_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified_again",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user has verified their accounts.",
                verbose_name="verified",
            ),
        ),
    ]
