# Generated by Django 4.2.4 on 2023-10-08 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_user_is_verified_again"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified_again",
        ),
    ]
