# Generated by Django 4.2.4 on 2023-10-11 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_remove_user_is_verified_again"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_codes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
