# Generated by Django 4.2.4 on 2023-10-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_alter_verificationcode_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcode",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="The phone number to which the code was sent.",
                max_length=20,
                null=True,
                verbose_name="phone number",
            ),
        ),
    ]
