# Generated by Django 4.2.4 on 2023-10-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_verificationcode_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="phone number"),
        ),
    ]
