# Generated by Django 4.2.4 on 2023-10-12 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_user_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="technician",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
