# Generated by Django 4.2.4 on 2023-10-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_techniciantype_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="The profile picture of the user.",
                null=True,
                upload_to="profile_pictures/",
                verbose_name="profile picture",
            ),
        ),
    ]
