# Generated by Django 4.2.4 on 2023-11-05 18:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_user_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicianCertificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="technicians-certificate/",
                        verbose_name="technician certificate",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="users.technician",
                        verbose_name="technician",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
