# Generated by Django 4.2.4 on 2023-11-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_techniciancertificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technician",
            name="certificate",
        ),
        migrations.AddField(
            model_name="technician",
            name="certificates",
            field=models.ManyToManyField(
                related_name="technicians", to="users.techniciancertificate", verbose_name="certificates"
            ),
        ),
    ]
