# Generated by Django 4.2.4 on 2023-12-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_remove_technician_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted"),
        ),
    ]
