# Generated by Django 4.2.4 on 2023-10-19 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("os", models.IntegerField(choices=[(0, "IOS"), (1, "Android")], verbose_name="os")),
                ("token", models.CharField(max_length=255, unique=True, verbose_name="token")),
                ("arn", models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="aen")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="notification type"),
                ),
                ("arn", models.CharField(blank=True, max_length=255, null=True, verbose_name="arn")),
                ("message", models.TextField(blank=True, null=True, verbose_name="message")),
                ("response", models.TextField(blank=True, null=True, verbose_name="response")),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="aws_sns.device",
                        verbose_name="device",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
