# Generated by Django 4.2.4 on 2023-11-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aws_sns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="arn",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="arn"),
        ),
    ]
